config/routes.rb
Rails.application.routes.draw do

  get "loadphasesproperties" ,to:"load#loadproperties"
  get "loadphases",to:"load#loadphases"
  get "/masterplan2d/:compoundmasterplan",to:"masterplan2ds#get"
  get "/getpropertydetails/:propertyid",to:"phasesproperties#get"
  # get "/masterplan2dfilterpropertytype/:propertytype",to:"filters#filterpropertytype"
  post "/filter/3dmodeling",to:"filters#filter_phase_3d"
  post "/filter/2dmodeling",to:"filters#filter_phase_2d"
  
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
   
    def phase_params
      params.fetch(:phase, {})
    end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_form.html.erb
<%= form_with(model: phase) do |form| %>
  <% if phase.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
        <% phase.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/phases/_phase.html.erb
<div id="<%= dom_id phase %>">
</div>

app/views/phases/edit.html.erb
<h1>Editing phase</h1>

<%= render "form", phase: @phase %>

<br>

<div>
  <%= link_to "Show this phase", @phase %> |
  <%= link_to "Back to phases", phases_path %>
</div>

app/views/phases/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Phases</h1>

<div id="phases">
  <% @phases.each do |phase| %>
    <%= render phase %>
    <p>
      <%= link_to "Show this phase", phase %>
    </p>
  <% end %>
</div>

<%= link_to "New phase", new_phase_path %>

app/views/phases/new.html.erb
<h1>New phase</h1>

<%= render "form", phase: @phase %>

<br>

<div>
  <%= link_to "Back to phases", phases_path %>
</div>

app/views/phases/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @phase %>

<div>
  <%= link_to "Edit this phase", edit_phase_path(@phase) %> |
  <%= link_to "Back to phases", phases_path %>

  <%= button_to "Destroy this phase", @phase, method: :delete %>
</div>